name: Run update-since-todo.py

on:
#  schedule:
#    - cron: "0 16 * * THU"
  workflow_dispatch:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  since_updater:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'timja' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run update-since-todo.py
        run: |
          body=$(./update-since-todo.py)
          
          echo "${body}"
          
          {
            echo 'PROGRESS<<EOF'
            echo "${body}"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        id: run_script
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fill in since annotations
          title: Fill in since annotations
          body: ${{ steps.run_script.outputs.PROGRESS }}
          base: master
          labels: skip-changelog
          delete-branch: true
